/* generated by build.ps1 from data/site.json - do not edit */
window.KG_SITE = {
  "name": "ウマぃ飯",
  "tagline": "競馬場の、うまい飯。",
  "description": "競馬場の名物グルメ・キッチンカー・イベントを、初めての人にも分かりやすく紹介するガイド",
  "baseUrl": "https://umaimeshi.zudia.jp",
  "cname": "umaimeshi.zudia.jp",
  "noindex": true,
  "basePath": "",
  "lang": "ja",
  "reviewFormUrl": "",
  "note": { "url": "", "label": "note で読む" },
  "promos": [
    { "id": "note",       "slots": ["inline"],                  "badge": "有料記事", "title": "", "text": "", "url": "", "buttonText": "note で読む" },
    { "id": "stay",       "slots": ["inline"],                  "badge": "PR",      "title": "", "text": "", "url": "", "buttonText": "宿泊先を探す" },
    { "id": "prediction", "slots": ["hero", "inline", "sticky"], "badge": "",        "title": "", "text": "", "url": "", "buttonText": "" }
  ],
  "prediction": { "name": "", "url": "", "ctaText": "今週の予想を無料で見る", "ctaSub": "" },
  "ga4Id": "",
  "twitter": "",
  "contactFormUrl": "",
  "contactEmail": ""
};
